### ISSUE TITLE
GDB linaro 7.8 build error

### ISSUE THREAD

**Issue by VishwanathPatil** [kraj/meta-linaro#2]
GDB linaro yocto link is no more valid . Build fails with ,

ERROR: gdb-linaro-7.8-r2014.09.arago0 do_fetch: Function failed: Fetcher failure for URL: 'https://releases.linaro.org/14.09/components/toolchain/gdb-linaro/gdb-linaro-7.8-2014.09.tar.xz'. Unable to fetch URL from any source.

**Comment by kraj** [comment]
@VishwanathPatil this layer is maintained by Linaro now see

https://git.linaro.org/openembedded/meta-linaro.git/

**Comment by VishwanathPatil** [comment]
older versions are maintained in archive folders .
